<?php

declare(strict_types=1);

namespace App\Module\Velox;

use App\Module\Velox\Plugin\DTO\Plugin;
use App\Module\Velox\Plugin\DTO\PluginCategory;
use App\Module\Velox\Plugin\DTO\PluginRepository;
use App\Module\Velox\Plugin\DTO\PluginSource;
use App\Module\Velox\Plugin\Service\CompositePluginProvider;
use App\Module\Velox\Plugin\Service\ConfigPluginProvider;
use App\Module\Velox\Plugin\Service\PluginProviderInterface;
use Spiral\Boot\Bootloader\Bootloader;
use Spiral\Boot\EnvironmentInterface;

final class PluginsBootloader extends Bootloader
{
    #[\Override]
    public function defineSingletons(): array
    {
        return [
            PluginProviderInterface::class => fn(
                EnvironmentInterface $env,
            ) => new CompositePluginProvider(
                providers: [
                    new ConfigPluginProvider([
                        ...$this->initCorePlugins($env),
                        ...$this->initCommonPlugins($env),
                    ]),
                ],
            ),
        ];
    }

    private function initCommonPlugins(EnvironmentInterface $env): array
    {
        return [
            new Plugin(
                name: 'sentry-collector',
                ref: $env->get('RR_PLUGIN_SENTRY_COLLECTOR', 'master'),
                owner: 'butschster',
                repository: 'rr-sentry-transport',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Community,
                description: 'Sentry collector plugin allowing delegation of Sentry events delivery to the Sentry server through the RoadRunner server.',
                category: PluginCategory::Monitoring,
            ),
            new Plugin(
                name: 'redis-queue',
                ref: $env->get('RR_PLUGIN_REDIS_QUEUE', 'master'),
                owner: 'ASG-Digital',
                repository: 'rr-redis-queue',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Community,
                description: 'This is a plugin for roadrunner adding support for a redis backed queue. This plugin is still under development and should not be considered production ready.',
                category: PluginCategory::Jobs,
            ),
        ];
    }

    private function initCorePlugins(EnvironmentInterface $env): array
    {
        return [
            new Plugin(
                name: 'appLogger',
                ref: $env->get('RR_PLUGIN_APP_LOGGER', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'app-logger',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['logger'],
                description: 'Application logger plugin for RoadRunner',
                category: PluginCategory::Logging,
            ),
            new Plugin(
                name: 'logger',
                ref: $env->get('RR_PLUGIN_LOGGER', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'logger',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                description: 'Core logging functionality',
                category: PluginCategory::Logging,
            ),
            new Plugin(
                name: 'server',
                ref: $env->get('RR_PLUGIN_SERVER', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'server',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                description: 'Core server functionality',
                category: PluginCategory::Core,
            ),
            new Plugin(
                name: 'http',
                ref: $env->get('RR_PLUGIN_HTTP', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'http',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['server'],
                description: 'HTTP server plugin',
                category: PluginCategory::Http,
            ),
            new Plugin(
                name: 'gzip',
                ref: $env->get('RR_PLUGIN_GZIP', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'gzip',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['http'],
                description: 'GZIP compression middleware',
                category: PluginCategory::Http,
            ),
            new Plugin(
                name: 'headers',
                ref: $env->get('RR_PLUGIN_HEADERS', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'headers',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['http'],
                description: 'HTTP headers middleware',
                category: PluginCategory::Http,
            ),
            new Plugin(
                name: 'static',
                ref: $env->get('RR_PLUGIN_STATIC', 'v5.0.1'),
                owner: 'roadrunner-server',
                repository: 'static',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['http'],
                description: 'Static file serving middleware',
                category: PluginCategory::Http,
            ),
            new Plugin(
                name: 'jobs',
                ref: $env->get('RR_PLUGIN_JOBS', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'jobs',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['server'],
                description: 'Job queue management',
                category: PluginCategory::Jobs,
            ),
            new Plugin(
                name: 'amqp',
                ref: $env->get('RR_PLUGIN_AMQP', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'amqp',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['jobs'],
                description: 'AMQP job driver',
                category: PluginCategory::Jobs,
            ),
            new Plugin(
                name: 'sqs',
                ref: $env->get('RR_PLUGIN_SQS', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'sqs',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['jobs'],
                description: 'AWS SQS job driver',
                category: PluginCategory::Jobs,
            ),
            new Plugin(
                name: 'beanstalk',
                ref: $env->get('RR_PLUGIN_BEANSTALK', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'beanstalk',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['jobs'],
                description: 'Beanstalk job driver',
                category: PluginCategory::Jobs,
            ),
            new Plugin(
                name: 'nats',
                ref: $env->get('RR_PLUGIN_NATS', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'nats',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['jobs'],
                description: 'NATS job driver',
                category: PluginCategory::Jobs,
            ),
            new Plugin(
                name: 'kafka',
                ref: $env->get('RR_PLUGIN_KAFKA', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'kafka',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['jobs'],
                description: 'Apache Kafka job driver',
                category: PluginCategory::Jobs,
            ),
            new Plugin(
                name: 'kv',
                ref: $env->get('RR_PLUGIN_KV', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'kv',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['server'],
                description: 'Key-value storage interface',
                category: PluginCategory::Kv,
            ),
            new Plugin(
                name: 'redis',
                ref: $env->get('RR_PLUGIN_REDIS', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'redis',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['kv'],
                description: 'Redis key-value storage',
                category: PluginCategory::Kv,
            ),
            new Plugin(
                name: 'memory',
                ref: $env->get('RR_PLUGIN_MEMORY', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'memory',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['kv'],
                description: 'In-memory key-value storage',
                category: PluginCategory::Kv,
            ),
            new Plugin(
                name: 'boltdb',
                ref: $env->get('RR_PLUGIN_BOLTDB', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'boltdb',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['kv'],
                description: 'BoltDB key-value storage',
                category: PluginCategory::Kv,
            ),
            new Plugin(
                name: 'memcached',
                ref: $env->get('RR_PLUGIN_MEMCACHED', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'memcached',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['kv'],
                description: 'Memcached key-value storage',
                category: PluginCategory::Kv,
            ),
            new Plugin(
                name: 'metrics',
                ref: $env->get('RR_PLUGIN_METRICS', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'metrics',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                description: 'Metrics collection and reporting',
                category: PluginCategory::Metrics,
            ),
            new Plugin(
                name: 'prometheus',
                ref: $env->get('RR_PLUGIN_PROMETHEUS', 'v5.0.1'),
                owner: 'roadrunner-server',
                repository: 'prometheus',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['metrics'],
                description: 'Prometheus metrics exporter',
                category: PluginCategory::Metrics,
            ),
            new Plugin(
                name: 'grpc',
                ref: $env->get('RR_PLUGIN_GRPC', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'grpc',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['server'],
                description: 'gRPC server plugin',
                category: PluginCategory::Grpc,
            ),
            new Plugin(
                name: 'rpc',
                ref: $env->get('RR_PLUGIN_RPC', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'rpc',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                description: 'RPC communication plugin',
                category: PluginCategory::Core,
            ),
            new Plugin(
                name: 'status',
                ref: $env->get('RR_PLUGIN_STATUS', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'status',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                description: 'Health checks and readiness probes',
                category: PluginCategory::Monitoring,
            ),
            new Plugin(
                name: 'fileserver',
                ref: $env->get('RR_PLUGIN_FILESERVER', 'v5.0.1'),
                owner: 'roadrunner-server',
                repository: 'fileserver',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['http'],
                description: 'Static file server',
                category: PluginCategory::Http,
            ),
            new Plugin(
                name: 'tcp',
                ref: $env->get('RR_PLUGIN_TCP', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'tcp',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['server'],
                description: 'Raw TCP payload handling',
                category: PluginCategory::Network,
            ),
            new Plugin(
                name: 'centrifuge',
                ref: $env->get('RR_PLUGIN_CENTRIFUGE', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'centrifuge',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['server'],
                description: 'Centrifuge broadcasting platform',
                category: PluginCategory::Broadcasting,
            ),
            new Plugin(
                name: 'temporal',
                ref: $env->get('RR_PLUGIN_TEMPORAL', 'v5.1.0'),
                owner: 'temporalio',
                repository: 'roadrunner-temporal',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['server'],
                description: 'Temporal workflow engine',
                category: PluginCategory::Workflow,
            ),
            new Plugin(
                name: 'otel',
                ref: $env->get('RR_PLUGIN_OTEL', 'v5.0.1'),
                owner: 'roadrunner-server',
                repository: 'otel',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                description: 'OpenTelemetry tracing',
                category: PluginCategory::Observability,
            ),
            new Plugin(
                name: 'service',
                ref: $env->get('RR_PLUGIN_SERVICE', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'service',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                description: 'Lightweight systemd-like service manager',
                category: PluginCategory::Core,
            ),
            new Plugin(
                name: 'lock',
                ref: $env->get('RR_PLUGIN_LOCK', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'lock',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                description: 'Distributed locking mechanism',
                category: PluginCategory::Core,
            ),
            new Plugin(
                name: 'proxy',
                ref: $env->get('RR_PLUGIN_PROXY', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'proxy_ip_parser',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['http'],
                description: 'Proxy IP parser middleware',
                category: PluginCategory::Http,
            ),
            new Plugin(
                name: 'send',
                ref: $env->get('RR_PLUGIN_SEND', 'v5.0.1'),
                owner: 'roadrunner-server',
                repository: 'send',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['http'],
                description: 'Send file response middleware',
                category: PluginCategory::Http,
            ),
            new Plugin(
                name: 'googlepubsub',
                ref: $env->get('RR_PLUGIN_GOOGLEPUBSUB', 'v5.0.2'),
                owner: 'roadrunner-server',
                repository: 'google-pub-sub',
                repositoryType: PluginRepository::Github,
                source: PluginSource::Official,
                dependencies: ['jobs'],
                description: 'Google Pub/Sub job driver',
                category: PluginCategory::Jobs,
            ),
        ];
    }
}
