<?php

declare(strict_types=1);

namespace App\Module\Velox;

use App\Module\Velox\DTO\Plugin;
use App\Module\Velox\DTO\PluginRepository;
use App\Module\Velox\DTO\PluginSource;
use App\Module\Velox\Service\CompositePluginProvider;
use App\Module\Velox\Service\ConfigPluginProvider;
use App\Module\Velox\Service\PluginProviderInterface;
use Spiral\Boot\Attribute\SingletonMethod;
use Spiral\Boot\Bootloader\Bootloader;

final class PluginsBootloader extends Bootloader
{
    #[SingletonMethod]
    public function initCorePlugins(): PluginProviderInterface
    {
        return new CompositePluginProvider(providers: [
            new ConfigPluginProvider([
                new Plugin(
                    name: 'appLogger',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'app-logger',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    description: 'Application logger plugin for RoadRunner',
                    category: 'Logging',
                ),
                new Plugin(
                    name: 'logger',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'logger',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Core logging functionality',
                    category: 'Logging',
                ),
                new Plugin(
                    name: 'server',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'server',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    description: 'Core server functionality',
                    category: 'Core',
                ),
                new Plugin(
                    name: 'http',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'http',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'HTTP server plugin',
                    category: 'HTTP',
                ),
                new Plugin(
                    name: 'gzip',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'gzip',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['http'],
                    description: 'GZIP compression middleware',
                    category: 'HTTP',
                ),
                new Plugin(
                    name: 'headers',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'headers',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['http'],
                    description: 'HTTP headers middleware',
                    category: 'HTTP',
                ),
                new Plugin(
                    name: 'static',
                    ref: 'v5.0.1',
                    owner: 'roadrunner-server',
                    repository: 'static',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['http'],
                    description: 'Static file serving middleware',
                    category: 'HTTP',
                ),
                new Plugin(
                    name: 'jobs',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'jobs',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Job queue management',
                    category: 'Jobs',
                ),
                new Plugin(
                    name: 'amqp',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'amqp',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['jobs'],
                    description: 'AMQP job driver',
                    category: 'Jobs',
                ),
                new Plugin(
                    name: 'sqs',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'sqs',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['jobs'],
                    description: 'AWS SQS job driver',
                    category: 'Jobs',
                ),
                new Plugin(
                    name: 'beanstalk',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'beanstalk',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['jobs'],
                    description: 'Beanstalk job driver',
                    category: 'Jobs',
                ),
                new Plugin(
                    name: 'nats',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'nats',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['jobs'],
                    description: 'NATS job driver',
                    category: 'Jobs',
                ),
                new Plugin(
                    name: 'kafka',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'kafka',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['jobs'],
                    description: 'Apache Kafka job driver',
                    category: 'Jobs',
                ),
                new Plugin(
                    name: 'kv',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'kv',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Key-value storage interface',
                    category: 'KV',
                ),
                new Plugin(
                    name: 'redis',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'redis',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['kv'],
                    description: 'Redis key-value storage',
                    category: 'KV',
                ),
                new Plugin(
                    name: 'memory',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'memory',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['kv'],
                    description: 'In-memory key-value storage',
                    category: 'KV',
                ),
                new Plugin(
                    name: 'boltdb',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'boltdb',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['kv'],
                    description: 'BoltDB key-value storage',
                    category: 'KV',
                ),
                new Plugin(
                    name: 'memcached',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'memcached',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['kv'],
                    description: 'Memcached key-value storage',
                    category: 'KV',
                ),
                new Plugin(
                    name: 'metrics',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'metrics',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Metrics collection and reporting',
                    category: 'Metrics',
                ),
                new Plugin(
                    name: 'prometheus',
                    ref: 'v5.0.1',
                    owner: 'roadrunner-server',
                    repository: 'prometheus',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['metrics'],
                    description: 'Prometheus metrics exporter',
                    category: 'Metrics',
                ),
                new Plugin(
                    name: 'grpc',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'grpc',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'gRPC server plugin',
                    category: 'gRPC',
                ),
                new Plugin(
                    name: 'rpc',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'rpc',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'RPC communication plugin',
                    category: 'Core',
                ),
                new Plugin(
                    name: 'status',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'status',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Health checks and readiness probes',
                    category: 'Monitoring',
                ),
                new Plugin(
                    name: 'fileserver',
                    ref: 'v5.0.1',
                    owner: 'roadrunner-server',
                    repository: 'fileserver',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Static file server',
                    category: 'HTTP',
                ),
                new Plugin(
                    name: 'tcp',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'tcp',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Raw TCP payload handling',
                    category: 'Network',
                ),
                new Plugin(
                    name: 'centrifuge',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'centrifuge',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Centrifuge broadcasting platform',
                    category: 'Broadcasting',
                ),
                new Plugin(
                    name: 'temporal',
                    ref: 'v5.1.0',
                    owner: 'temporalio',
                    repository: 'roadrunner-temporal',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Temporal workflow engine',
                    category: 'Workflow',
                ),
                new Plugin(
                    name: 'otel',
                    ref: 'v5.0.1',
                    owner: 'roadrunner-server',
                    repository: 'otel',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'OpenTelemetry tracing',
                    category: 'Observability',
                ),
                new Plugin(
                    name: 'service',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'service',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Lightweight systemd-like service manager',
                    category: 'Core',
                ),
                new Plugin(
                    name: 'lock',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'lock',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['server'],
                    description: 'Distributed locking mechanism',
                    category: 'Core',
                ),
                new Plugin(
                    name: 'proxy',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'proxy_ip_parser',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['http'],
                    description: 'Proxy IP parser middleware',
                    category: 'HTTP',
                ),
                new Plugin(
                    name: 'send',
                    ref: 'v5.0.1',
                    owner: 'roadrunner-server',
                    repository: 'send',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['http'],
                    description: 'Send file response middleware',
                    category: 'HTTP',
                ),
                new Plugin(
                    name: 'googlepubsub',
                    ref: 'v5.0.2',
                    owner: 'roadrunner-server',
                    repository: 'google-pub-sub',
                    repositoryType: PluginRepository::Github,
                    source: PluginSource::Official,
                    dependencies: ['jobs'],
                    description: 'Google Pub/Sub job driver',
                    category: 'Jobs',
                ),
            ]),
        ]);
    }
}

