version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

http:
  address: '0.0.0.0:8080'
  middleware:
    - gzip
  pool:
    debug: true
    supervisor:
      max_worker_memory: 100

server:
  command: 'php app.php'
  relay: pipes

temporal:
  address: '127.0.0.1:7233'
