version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

metrics:
  address: ":2112"

http:
  address: '0.0.0.0:8080'
  middleware:
    - gzip
    - headers
    - sendfile
  headers:
    cors:
      allowed_origin: ${RR_CORS_ALLOWED_ORIGIN:-*}
      allowed_headers: ${RR_CORS_ALLOWED_HEADERS:-*}
      allowed_methods: ${RR_CORS_ALLOWED_METHODS:-GET,POST,PUT,DELETE}
      allow_credentials: false
      exposed_headers: ${RR_CORS_EXPOSED_HEADERS:-Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,Content-Disposition,X-RateLimit-Remaining,X-RateLimit-Retry-After,X-RateLimit-Limit,X-Captcha}
      max_age: 600
  pool:
    debug: ${HTTP_WORKERS_DEBUG:-false}
    num_workers: ${RR_HTTP_NUM_WORKERS:-4}
    supervisor:
      max_worker_memory: ${RR_HTTP_MAX_WORKER_MEMORY:-128}

kv:
  memory:
    driver: memory
    config: { }

cron:
  timezone: "UTC"
  grace_period: "30s"

  jobs:
    - name: "discover-community-plugins"
      command: "php app.php velox:discover-plugin"
      schedule: "0 */1 * * *"
      allow_overlap: false
      timeout: "5m"
      log_file: "runtime/logs/discover-plugins.log"
      max_log_size: 10485760
      max_log_files: 5

server:
  command: 'php app.php'
  relay: pipes

#s3:
#  default: uploads
#  servers:
#    do:
#      region: ${AWS_DEFAULT_REGION:-us-east-1}
#      endpoint: ${AWS_ENDPOINT:-https://fra1.digitaloceanspaces.com}
#      credentials:
#        key: ${AWS_KEY}
#        secret: ${AWS_SECRET}
#
#  buckets:
#    uploads:
#      server: do
#      bucket: ${AWS_BUCKET:-uploads}
#      visibility: public