version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

http:
  address: '0.0.0.0:8080'
  middleware:
    - gzip
  pool:
    num_workers: ${RR_HTTP_NUM_WORKERS:-4}
    supervisor:
      max_worker_memory: ${RR_HTTP_MAX_WORKER_MEMORY:-128}

server:
  command: 'php app.php'
  relay: pipes

#temporal:
#  address: '127.0.0.1:7233'
